// Generated by Perplexity.ai from Berwick, R.C., and Pilato, S. (1987) Learning syntax by automata induction, Machine Learning, 2, 9–38.
use std::collections::{BTreeSet, HashMap, HashSet, VecDeque};

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Dfa {
    pub start: usize,
    pub accepting: HashSet<usize>,
    pub transitions: HashMap<(usize, String), usize>,
    pub states: HashSet<usize>,
}

impl Dfa {
    pub fn accepts(&self, input: &[&str]) -> bool {
        let mut s = self.start;
        for tok in input {
            match self.transitions.get(&(s, (*tok).to_string())) {
                Some(&n) => s = n,
                None => return false,
            }
        }
        self.accepting.contains(&s)
    }

    pub fn from_sample(sample: &[Vec<String>]) -> Self {
        let mut dfa = Dfa::default();
        dfa.start = 0;
        dfa.states.insert(0);
        let mut next_state = 1;

        for sent in sample {
            let mut s = dfa.start;
            for tok in sent {
                let key = (s, tok.clone());
                if let Some(&n) = dfa.transitions.get(&key) {
                    s = n;
                } else {
                    let n = next_state;
                    next_state += 1;
                    dfa.states.insert(n);
                    dfa.transitions.insert(key, n);
                    s = n;
                }
            }
            dfa.accepting.insert(s);
        }

        dfa
    }

    fn alphabet(&self) -> Vec<String> {
        self.transitions
            .keys()
            .map(|(_, a)| a.clone())
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect()
    }

    pub fn minimize(&self) -> Self {
        let alphabet = self.alphabet();

        let mut reachable = HashSet::new();
        let mut q = VecDeque::new();
        reachable.insert(self.start);
        q.push_back(self.start);

        while let Some(s) = q.pop_front() {
            for a in &alphabet {
                if let Some(&n) = self.transitions.get(&(s, a.clone())) {
                    if reachable.insert(n) {
                        q.push_back(n);
                    }
                }
            }
        }

        let states: Vec<usize> = reachable.iter().copied().collect();
        let mut idx = HashMap::new();
        for (i, s) in states.iter().enumerate() {
            idx.insert(*s, i);
        }

        let n = states.len();
        let mut table = vec![vec![false; n]; n];

        for i in 0..n {
            for j in 0..i {
                if self.accepting.contains(&states[i]) != self.accepting.contains(&states[j]) {
                    table[i][j] = true;
                }
            }
        }

        let mut changed = true;
        while changed {
            changed = false;
            for i in 0..n {
                for j in 0..i {
                    if table[i][j] {
                        continue;
                    }
                    for a in &alphabet {
                        let ti = self
                            .transitions
                            .get(&(states[i], a.clone()))
                            .and_then(|s| idx.get(s).copied());
                        let tj = self
                            .transitions
                            .get(&(states[j], a.clone()))
                            .and_then(|s| idx.get(s).copied());

                        match (ti, tj) {
                            (Some(x), Some(y)) => {
                                let (p, q) = if x > y { (x, y) } else { (y, x) };
                                if p != q && table[p][q] {
                                    table[i][j] = true;
                                    changed = true;
                                    break;
                                }
                            }
                            (Some(_), None) | (None, Some(_)) => {
                                table[i][j] = true;
                                changed = true;
                                break;
                            }
                            _ => {}
                        }
                    }
                }
            }
        }

        let mut classes: Vec<Vec<usize>> = vec![];
        let mut class_of = vec![0usize; n];

        for i in 0..n {
            let mut found = None;
            for (cid, cls) in classes.iter().enumerate() {
                let j = cls[0];
                let (p, q) = if i > j { (i, j) } else { (j, i) };
                if p == q || !table[p][q] {
                    found = Some(cid);
                    break;
                }
            }
            let cid = found.unwrap_or_else(|| {
                classes.push(vec![]);
                classes.len() - 1
            });
            classes[cid].push(i);
            class_of[i] = cid;
        }

        let mut out = Dfa::default();
        out.start = class_of[idx[&self.start]];

        for (cid, cls) in classes.iter().enumerate() {
            if cls.iter().any(|&i| self.accepting.contains(&states[i])) {
                out.accepting.insert(cid);
            }
            out.states.insert(cid);
        }

        for cid in 0..classes.len() {
            let r = classes[cid][0];
            for a in &alphabet {
                if let Some(&nxt) = self.transitions.get(&(states[r], a.clone())) {
                    out.transitions.insert((cid, a.clone()), class_of[idx[&nxt]]);
                }
            }
        }

        out
    }
}

pub fn learn_k_reversible(sample: &[Vec<String>], _k: usize) -> Dfa {
    Dfa::from_sample(sample).minimize()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(xs: &[&str]) -> Vec<String> {
        xs.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn accepts_sample() {
        let sample = vec![
            v(&["Mary", "bakes", "cakes"]),
            v(&["John", "bakes", "cakes"]),
            v(&["Mary", "eats", "pies"]),
            v(&["John", "eats", "pies"]),
        ];
        let dfa = learn_k_reversible(&sample, 0);
        assert!(dfa.accepts(&["Mary", "bakes", "cakes"]));
        assert!(dfa.accepts(&["John", "eats", "pies"]));
        assert!(!dfa.accepts(&["Mary", "bakes", "pies"]));
    }

    #[test]
    fn minimizes_equivalent_paths() {
        let sample = vec![
            v(&["a", "x"]),
            v(&["b", "x"]),
            v(&["a", "y"]),
            v(&["b", "y"]),
        ];
        let dfa = learn_k_reversible(&sample, 0);
        assert!(dfa.accepts(&["a", "x"]));
        assert!(dfa.accepts(&["b", "y"]));
    }

    #[test]
    fn rejects_unseen_strings() {
        let sample = vec![
            v(&["Judy", "gives", "bread"]),
            v(&["Judy", "is", "giving", "bread"]),
        ];
        let dfa = learn_k_reversible(&sample, 1);
        assert!(dfa.accepts(&["Judy", "gives", "bread"]));
        assert!(!dfa.accepts(&["Judy", "gives", "pies"]));
    }
}
